# installation of cython is a workaround for tinydtls-cython that should be avoided there
#
# running tests twice, so if something breaks when optional dependencies are
# missing, it still shows up. (full coverage would mean running each
# combination, but let's not blow the test matrix out of proportion).
test:3.6:
  image: "python:3.6-stretch"
  script:
    - echo Using cache:; ls .eggs/ || echo No cached .eggs found
    - rm -f .coverage* collected-coverage/3.6/
    - pip3 install coverage
    - AIOCOAP_TEST_EXTRAS= python3 -m coverage run --parallel ./setup.py test
    - python3 -m coverage run --parallel ./setup.py test
    - pip3 install uvloop
    - AIOCOAP_TESTS_LOOP=uvloop python3 -m coverage run --parallel ./setup.py test
    - python3 -m coverage combine
    - python3 -m coverage report --include=aiocoap/\*
    - mkdir collected-coverage/3.6/ -p
    - mv .coverage* collected-coverage/3.6/
  artifacts:
    paths:
      - collected-coverage
  cache:
    key: python3.6
    paths:
      - .eggs/

test:3.5:
  # plain python:3.5 (which is based on jessie) has too old OpenSSL to support
  # cryptography's AEAD, and python:3.5-stretch is not available from the
  # official docker hub python containers.
  image: "python:3.5-jessie"
  script:
    - echo deb http://ftp.debian.org/debian jessie-backports main >> /etc/apt/sources.list
    - apt-get update
    - apt-get -y -t jessie-backports install libssl-dev
    - echo Using cache:; ls .eggs/ || echo No cached .eggs found
    - AIOCOAP_TEST_EXTRAS= ./setup.py test
    - ./setup.py test
    - pip3 install uvloop
    - AIOCOAP_TESTS_LOOP=uvloop ./setup.py test
  cache:
    key: python3.5
    paths:
      - .eggs/

pages:
  image: "python:3.6-stretch"
  stage: deploy
  dependencies:
    - test:3.6
  script:
    - pip3 install coverage
    - rm -f .coverage* public
    - mv collected-coverage/*/.coverage* .
    - python3 -m coverage html --include=aiocoap/\*
    - mv htmlcov public
  artifacts:
    paths:
      - public
