language: python
python:
 - 2.7
 - 3.5
 - 3.6
 - nightly
install:
 - pip install pytest-cov
 - pip install coveralls
script:
 - py.test --cov=python --cov-branch python/test/

after_success:
 - coveralls
